create database salesdata;
use salesdata;
---# 1) Retrive all data from sales_data_project
select * from sales_data_project;

---# 2)Find count of the sales_data_project
select count(*) as Totalnumber from sales_data_project;

 ---# 3) List all unique product categories
SELECT DISTINCT Category FROM sales_data_project;

---# 4) What is the total number of units sold?
SELECT SUM(UnitsSold) AS TotalUnits FROM sales_data_project;

 ---# 5) What is the average price of products sold?
 SELECT Avg(price) AS Avg_Price from sales_data_project;
 
 ---# 6) Which region has the highest total sales?
SELECT Region,max(NetSales) AS max_Sales from sales_data_project
group by Region
order by max_sales desc
limit 1;

--# 7) How many units were sold in each region?
select Region,sum(UnitsSold) AS T_U from sales_data_project
group by Region;

--# 8) What is the total profit generated by each category ?  
select category,sum(Profit) As Total_Profit from sales_data_project
group by category; 

 ---# 9) What is the total discount given?
 select sum(DiscountAmount) As Total_discount from sales_data_project;
 
 ---# 10)Which product generated the highest profit?
select ProductName,sum(Profit) As Total_Profit from sales_data_project
group by ProductName
order by Total_Profit desc
limit 1;

---# 11)-- Which product category has the highest gross sales?
select category,sum(grossSales) As TotalGrossSales from sales_data_project
group by category
order by TotalGrossSales desc
limit 1;

---# 12 - Which category has the highest total sales in North America?
select category,sum(NetSales) as TotalSales from sales_data_project
where Region = "North America"
group by category
order by TotalSales desc
limit 1;

--# 13 What is the total loss (if any) across all transactions?
select sum(profit) as Total_Loss from sales_data_project
where profit < 0;

---# 14 - Which category has the highest total discount in Asia?
select category,sum(Discount) as TotalDiscount from sales_data_project
where Region = "asia"
group by category
order by  TotalDiscount desc
limit 1;

#--15-How many discount of each product?
select ProductName,sum(DiscountAmount) as Total_DA from sales_data_project
group by ProductName;

#--16 -- What are the monthly total sales? 
SELECT DATE_FORMAT(Date, '%Y-%m') AS Month, SUM(NetSales) AS MonthlySales 
FROM sales_data_project
GROUP BY Month 
ORDER BY Month;

#-17 What are the top 3 most profitable regions for the Electronics category?
SELECT Region, SUM(Profit) AS TotalProfit 
FROM sales_data_project 
WHERE Category = 'Electronics' 
GROUP BY Region 
ORDER BY TotalProfit DESC 
LIMIT 3;

#18-- Which month had the lowest profit?
SELECT DATE_FORMAT(Date, '%Y-%m') AS Month, SUM(Profit) AS MonthlyProfit 
FROM sales_data_project
GROUP BY Month 
ORDER BY MonthlyProfit ASC 
LIMIT 1;

#19-- Which product generated the highest profit?
SELECT ProductName, SUM(Profit) AS TotalProfit 
FROM sales_data_project
GROUP BY ProductName 
ORDER BY TotalProfit DESC 
LIMIT 1;

#--20 Identify products with above-average sales and below-average profit.
SELECT ProductName, NetSales, Profit 
FROM sales_data_project 
WHERE NetSales > (SELECT AVG(NetSales) FROM sales_data_project) 
  AND Profit < (SELECT AVG(Profit) FROM sales_data_project);



 



